# Generated by Django 4.0 on 2024-06-11 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='partcipants',
            field=models.ManyToManyField(blank=True, related_name='partcipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
