# Generated by Django 4.0 on 2024-06-11 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_cohort_partcipants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='partcipants',
        ),
        migrations.AddField(
            model_name='cohort',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
