# Generated by Django 4.0 on 2024-06-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cohort_partcipants_cohort_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='visibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.visibility'),
        ),
    ]
